
create user c##human identified by human;
grant connect,resource,dba to c##human;

DROP TABLE hobby;
DROP TABLE customer ;

-- CUSTOMER 테이블 생성 (ID 컬럼 자동 증가)
CREATE TABLE customer (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
NAME VARCHAR2(50),
AGE NUMBER,
HEIGHT NUMBER,
BIRTHDAY DATE
);

-- HOBBY 테이블 생성 (ID 컬럼 자동 증가)
CREATE TABLE hobby (
ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
CUSTOMER_ID NUMBER REFERENCES customer(ID),
HOBBY VARCHAR2(50)
);
INSERT INTO customer (NAME, AGE, HEIGHT, BIRTHDAY) VALUES ('김철수', 30, 175, TO_DATE('1994-04-15', 'YYYY-MM-DD'));
INSERT INTO customer (NAME, AGE, HEIGHT, BIRTHDAY) VALUES ('이영희', 25, 162, TO_DATE('1999-06-22', 'YYYY-MM-DD'));
INSERT INTO customer (NAME, AGE, HEIGHT, BIRTHDAY) VALUES ('박민수', 28, 180, TO_DATE('1996-02-10', 'YYYY-MM-DD'));
INSERT INTO customer (NAME, AGE, HEIGHT, BIRTHDAY) VALUES ('전소영', 27, 168, TO_DATE('1997-11-08', 'YYYY-MM-DD'));
INSERT INTO customer (NAME, AGE, HEIGHT, BIRTHDAY) VALUES ('최지훈', 35, 182, TO_DATE('1989-07-25', 'YYYY-MM-DD'));
INSERT INTO customer (NAME, AGE, HEIGHT, BIRTHDAY) VALUES ('정수진', 22, 158, TO_DATE('2002-05-30', 'YYYY-MM-DD'));
INSERT INTO customer (NAME, AGE, HEIGHT, BIRTHDAY) VALUES ('오지훈', 40, 185, TO_DATE('1984-01-12', 'YYYY-MM-DD'));
INSERT INTO customer (NAME, AGE, HEIGHT, BIRTHDAY) VALUES ('김나연', 31, 170, TO_DATE('1993-09-05', 'YYYY-MM-DD'));
INSERT INTO customer (NAME, AGE, HEIGHT, BIRTHDAY) VALUES ('유현우', 29, 178, TO_DATE('1995-08-17', 'YYYY-MM-DD'));
INSERT INTO customer (NAME, AGE, HEIGHT, BIRTHDAY) VALUES ('한서윤', 26, 165, TO_DATE('1998-12-03', 'YYYY-MM-DD'));

COMMIT;
INSERT INTO hobby (CUSTOMER_ID, HOBBY) VALUES (1, '축구');
INSERT INTO hobby (CUSTOMER_ID, HOBBY) VALUES (2, '농구');
INSERT INTO hobby (CUSTOMER_ID, HOBBY) VALUES (3, '독서');
INSERT INTO hobby (CUSTOMER_ID, HOBBY) VALUES (4, '요리');
INSERT INTO hobby (CUSTOMER_ID, HOBBY) VALUES (5, '등산');
INSERT INTO hobby (CUSTOMER_ID, HOBBY) VALUES (6, '사진 촬영');
INSERT INTO hobby (CUSTOMER_ID, HOBBY) VALUES (7, '배드민턴');
INSERT INTO hobby (CUSTOMER_ID, HOBBY) VALUES (8, '골프');
INSERT INTO hobby (CUSTOMER_ID, HOBBY) VALUES (9, '요가');
INSERT INTO hobby (CUSTOMER_ID, HOBBY) VALUES (10, '피아노 연주');

COMMIT;
